companieshouse/lfp-appeals-frontend

gulpfile.js, package-lock.json, package.json
This pull request added the ability to run the project locally with auto-reloading after changes are made.
=> build: added watch ability to project

.mocharc.json, package-lock.json, package.json, src/controllers/HealthCheckController.ts, test/ApplicationFactory.ts, test/SubstituteFactory.ts, test/controllers/HealthCheckController.test.ts
Change introduces sample integration test for one of our routes.
In provided example DI is configured with service substitutes with ping method configured specifically to simulate happy and unhappy behaviour.
=> Add integration test for health check endpoint

.github/PULL_REQUEST_TEMPLATE.md
N/A
Adds merge instructions to pull request template
=> chore: add merge instructions to pull request template

package-lock.json, package.json
N/A
Make 'eslint' explicit dependency to fix vulnerability in transitive dependency
```
``` …
=> build: make 'eslint' explicit dependency to fix vulnerability in transitive dependency

src/Server.ts, src/controllers/OtherReasonController.ts, src/controllers/index.ts, src/public/sass/application.scss, src/public/sass/other-reason/_extra-styles.scss, src/public/sass/patterns/_related-items.scss, src/utils/ConfigLoader.ts, src/utils/Paths.ts, src/views/layout.njk, src/views/other-reason-disclaimer.njk, test/ApplicationFactory.ts, test/controllers/OtherReasonController.test.ts
Also refactored code to extract express app config so it can be used in tests.
https://companieshouse.atlassian.net/browse/LFA-1272
Added a new controller to handle the new route for the "Other Reason Disclaimer Screen".
Extracted the config of the express app into a function so it can be reused in the tests.
Created simple unit test.
- [ * ] Tests added where applicable
- [ * ] UI changes look good on mobile
- [ * ] UI changes meet accessibility criteria
```
```
- feat: a …
=> feat: Other reason disclaimer screen

package-lock.json, package.json, src/utils/validation/SchemaValidator.ts, src/utils/validation/ValidationError.ts, src/utils/validation/ValidationResult.ts, test/utils/validation/SchemaValidator.test.ts, test/utils/validation/ValidationError.test.ts, test/utils/validation/ValidationResult.test.ts
None
Add schema validator
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, …
=> chore: add schema validator

.env.local, src/ContainerFactory.ts
N/A
Changed use of redis port and host to use the full url.
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, …
=> refactor: change redis creation to use url

src/Server.ts
N/A
There was an issue when running the app using node because the import in the Server.ts was importing `./controllers/Index` instead of `./controllers/index`
```
``` …
=> fix: Changed controllers/Index to controllers/index

package.json
None
Fixes CLI test runner so that it picks up all tests. Previous only 3 tests were picked up ignoring nested folders.
```
```
- types other than `fix:` and `feat:` …
=> test: fix CLI test runner so that it picks up all tests

src/controllers/PenaltyDetailsController.ts, test/controllers/PenaltyDetailsController.test.ts
https://companieshouse.atlassian.net/browse/LFA-1275
Added transition between penalty details entry page and disclaimer page.
```
``` …
=> feat: link between penalty details page and disclaimer

src/controllers/EntryController.ts, src/controllers/LandingController.ts, src/controllers/index.ts, src/utils/Paths.ts, test/controllers/EntryController.test.ts
N/A
add entryController with tests for redirecting '/start'
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, …
=> feat: add EntryController with tests for redirecting '/start'

src/views/landing.njk, src/views/other-reason-disclaimer.njk
No JIRA
Added ID to Start/Continue button on Landing and Disclaimer page
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, …
=> refactor: added id to buttons on landing and disclaimer pages

.gitignore, gulpfile.js, package.json, src/utils/ConfigLoader.ts
N/A
build: rename build to dist
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, …
=> build: rename build to dist

.editorconfig
None
Adds editor config that sets 4 spaces for indentation for every file type.
Reformatting will be done in separate PR.
```
``` …
=> chore: add editor config

src/middleware/SessionMocker.ts
https://companieshouse.atlassian.net/browse/LFA-1282
Address error from pipeline:
```
/tmp/build/a63a1b38/source-code/src/middleware/SessionMocker.ts:19:9
ERROR: 19:9  typedef  expected call-signature: 'getValue' to have a typedef
ERROR: 26:9  typedef  expected call-signature: 'getExtraData' to have a typedef
```
```
```
- BREAKING CHANGE: a commit that has a …
=> fix: update session mocker

test/controllers/CheckYourAppealController.test.ts
https://companieshouse.atlassian.net/browse/LFA-1282
update test to fix endless build
```
``` …
=> fix: update test to fix endless build

src/controllers/CheckYourAppealController.ts, src/utils/ConfigLoader.ts, src/utils/Paths.ts, test/controllers/CheckYourAppealController.test.ts
change summary appeal URI constant name
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, `style:`, …
=> refactor: change summary appeal URI constant name

src/middleware/AuthMiddleware.ts
=> fix: update signin return url

src/controllers/OtherReasonController.ts, test/controllers/OtherReasonController.test.ts
https://companieshouse.atlassian.net/browse/LFA-1400
Added transition from other reasons screen to check appeal screen
```
```
- types other than `fix:` and `feat:` …
=> feat: Transition from other reasons screen to check appeal screen

src/middleware/AuthMiddleware.ts
N/A
Added temp logs to AuthMiddleware for debugging 
```
``` …
=> log: Added logs to auth middleware

package-lock.json, package.json, routes.yaml, src/controllers/OtherReasonController.ts, src/controllers/PenaltyDetailsController.ts, src/middleware/AuthMiddleware.ts, test/ApplicationFactory.ts, test/utils/session/FakeSessionFactory.ts
N/A
This PR will point to a new branch of the node session handler which contains fixes to previous bugs and basic logging.
```
``` …
=> Fix: Fixed session middleware and added logs to auth middleware

package-lock.json, package.json
=> fix: Fix on node session handler side to address date.now() precision

src/views/landing.njk
No JIRA
Updated ID on 'start now' button
=> refactor: update start now button id on landing page

package-lock.json, package.json
None
Change adds `husky` that installs the following hooks:
- `pre-commit` that runs code linting
` `pre-push` that runs tests
If any of the scripts failed then git operation is cancelled. This way it helps prevent sharing bad quality code which does not pass test.
Above hooks can be skipped by adding `-no-verify` flag to git commands.
```
```
- BREAKING CHANGE: a …
=> workflow: introduce git hooks that run code linting and testing

src/controllers/CheckYourAppealController.ts, src/controllers/ConfirmationController.ts
N/A
Applied missing APPEAL_KEY constant to controllers.
```
``` …
=> fix: applied APPEAL_KEY to all missing controllers

start.sh
N/A
Fix start script for local vagrant configuration.
```
``` …
=> Fix start.sh script for local vagrant environment

src/controllers/CheckYourAppealController.ts, test/controllers/CheckYourAppealController.test.ts
https://companieshouse.atlassian.net/browse/LFA-1475
feat: add company number in subject line
```
``` …
=> feat: add company number in subject line

src/controllers/BaseController.ts, src/controllers/CheckYourAppealController.ts, src/controllers/ConfirmationController.ts, src/controllers/OtherReasonController.ts, src/controllers/OtherReasonDisclaimerController.ts, src/controllers/PenaltyDetailsController.ts, src/controllers/SafeNavigationBaseController.ts, src/controllers/processors/FormSubmissionProcessor.ts, src/controllers/processors/InternalEmailFormSubmissionProcessor.ts, src/controllers/processors/UpdateSessionFormSubmissionProcessor.ts, src/controllers/processors/UserEmailFormSubmissionProcessor.ts, src/models/Appeal.ts, src/models/ApplicationData.ts, test/controllers/BaseController.test.ts, test/controllers/CheckYourAppealController.test.ts, test/controllers/ConfirmationController.test.ts, test/controllers/EntryController.test.ts, test/controllers/OtherReasonController.test.ts, test/controllers/OtherReasonDisclaimerController.test.ts, test/controllers/PenaltyDetailsController.test.ts, test/controllers/SafeNavigationBaseController.test.ts, test/controllers/processors/InternalEmailFormSubmissionProcessor.test.ts, test/controllers/processors/UserEmailFormSubmissionProcessor.test.ts
https://companieshouse.atlassian.net/browse/LFA-1401
Session structure will now include permissions for navigation. For a user to enter a particular page it will have to have received permissions by the previous page in the user journey. The only pages that don't require permissions are the landing page (throwaway) and the penalty details page
```
```
- BREAKING …
=> feat: protect application from skipping journey steps

src/controllers/SafeNavigationBaseController.ts, test/controllers/SafeNavigationBaseController.test.ts
=> fix: allow change button to redirect

.env.local, .env.vagrant, src/utils/ConfigLoader.ts, src/views/landing.njk, src/views/layout.njk
https://companieshouse.atlassian.net/browse/LFA-1523
Adds PIWIK tracking code to application.
In addition to default tracking it also tracks "Start now" button clicks as tracking goal.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be …
=> feat: add PIWIK tracking code and define goal on start now button

.env.local, .env.vagrant, package-lock.json, package.json, src/ContainerFactory.ts, src/controllers/BaseController.ts, src/controllers/CheckYourAppealController.ts, src/controllers/ConfirmationController.ts, src/controllers/OtherReasonController.ts, src/controllers/PenaltyDetailsController.ts, src/controllers/SafeNavigationBaseController.ts, src/controllers/processors/AppealStorageFormSubmissionProcessor.ts, src/controllers/processors/InternalEmailFormSubmissionProcessor.ts, src/controllers/processors/UpdateSessionFormSubmissionProcessor.ts, src/controllers/processors/UserEmailFormSubmissionProcessor.ts, src/middleware/AuthMiddleware.ts, src/middleware/ErrorHandler.ts, src/middleware/Logger.ts, src/modules/email-publisher/EmailService.ts, src/service/AppealStorageService.ts, src/utils/ConfigLoader.ts, tsconfig.json
https://companieshouse.atlassian.net/browse/LFA-1582
Added the ch logging framework's middleware to log all requests and extra debug logs to files.
```
```
- types …
=> feat: added ch logging

src/views/landing.njk
https://companieshouse.atlassian.net/browse/LFA-1602
Removes content from landing page.
```
``` …
=> chore: remove requirement for auth code from landing page

src/views/evidence-upload.njk
No JIRA
Added identifier to 'add document' button on evidence-upload.njk for testing
```
``` …
=> chore: add id to 'add document' button on evidence-upload template

test/controllers/EvidenceDownloadController.test.ts, test/service/FileTransferService.test.ts
N/A
`Readable.from` only exists for node version > 12.3.0 which caused the failure in the pipeline since the node version running on the environments is <12.3.0
```
``` …
=> fix: fixed issue with Readable.from

src/views/evidence-upload.njk
N/A
Change requested by Richard
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, …
=> fix: facilitate testing of upload page

src/views/evidence-removal.njk, test/controllers/EvidenceRemovalController.test.ts
Changed Message Header titletext to read 'There is a problem'.
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, …
=> chore: change title of error summary box on the evidence removal page

src/views/evidence-upload.njk
N/A
Address issues for QA pointed out by Richard
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, `style:`, …
=> fix: address QA Issues on upload page template

src/modules/file-transfer-service/FileMetadata.ts, src/modules/file-transfer-service/FileTransferService.ts, test/controllers/EvidenceDownloadController.test.ts, test/modules/file-transfer-service/FileTransferService.test.ts
=> refactor: move file metadata close to file transfer service and correct AV status

test/ApplicationFactory.ts, test/controllers/CheckYourAppealController.test.ts, test/controllers/ConfirmationController.test.ts, test/controllers/EvidenceRemovalController.test.ts, test/controllers/EvidenceUploadController.test.ts, test/controllers/OtherReasonController.test.ts, test/controllers/OtherReasonDisclaimerController.test.ts, test/controllers/PenaltyDetailsController.test.ts, test/middleware/AuthMiddleware.test.ts, test/middleware/FileTransferFeatureMiddleware.test.ts
=> refactor: move session creation to application factory

package-lock.json, src/controllers/processors/AppealStorageFormActionProcessor.ts, src/controllers/processors/InternalEmailFormActionProcessor.ts, src/middleware/AuthMiddleware.ts, src/models/Appeal.ts, src/utils/UriFactory.ts, test/controllers/processors/InternalEmailFormSubmissionProcessor.test.ts
https://companieshouse.atlassian.net/browse/LFA-1464
Change adds list of attachments to email data so that file links can be rendered in the email.
```
```
- types …
=> feat: include attached evidence in internal Companies House email

src/views/evidence-upload.njk, test/controllers/EvidenceUploadController.test.ts
https://companieshouse.atlassian.net/browse/LFA-1278
Updated error message on document upload
```
``` …
=> fix: update error message on evidence upload page

src/controllers/OtherReasonController.ts, src/controllers/PenaltyDetailsController.ts, src/controllers/SafeNavigationBaseController.ts
None
As per title...
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, …
=> reafctor: sync SafeNavigationBaseController constructor with base class

src/controllers/EvidenceUploadController.ts, src/controllers/OtherReasonController.ts, src/middleware/FileTransferFeatureMiddleware.ts, src/utils/Feature.ts, src/utils/FeatureChecker.ts, test/controllers/EvidenceUploadController.test.ts, test/controllers/OtherReasonController.test.ts, test/middleware/FileTransferFeatureMiddleware.test.ts, test/utils/FeatureChecker.ts
https://companieshouse.atlassian.net/browse/LFA-1281
https://companieshouse.atlassian.net/browse/LFA-1276
Conditional page transitions to and from file upload page. Handling of "Continue without adding documents" link will be added in separate pull request.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change …
=> feat: add page transitions to and from file upload page

.gitignore, .nycrc.json, Makefile, package-lock.json, package.json, sonar-project.properties
https://companieshouse.atlassian.net/browse/LFA-1598
NPM task that analyses code using SonarQube.
```
```
- types other than `fix:` and `feat:` are allowed, for …
=> chore: add task that analyses code using SonarQube

src/controllers/EvidenceDownloadController.ts
Change differs setting content disposition header until file can be disposed.
```
``` …
=> fix: fix error page rendering when downloaded file is not scanned or infected

src/controllers/EvidenceDownloadController.ts, test/controllers/EvidenceDownloadController.test.ts
=> test: add verification of content disposition header to file download tests

src/views/check-your-appeal.njk, src/views/confirmation.njk, test/controllers/CheckYourAppealController.test.ts
https://companieshouse.atlassian.net/browse/LFA-1451
Updated 'Check your appeal' page to include list of supporting documents for appal or 'None'
=> feat: check files before submission

src/controllers/EvidenceQuestionController.ts, src/controllers/index.ts, src/utils/Paths.ts, src/views/evidence-question.njk, test/controllers/EvidenceQuestionController.test.ts
https://companieshouse.atlassian.net/browse/LFA-1277
```
``` …
=> feat: add evidence question page

src/controllers/CheckYourAppealController.ts, src/controllers/EvidenceQuestionController.ts, src/controllers/EvidenceUploadController.ts, src/views/evidence-question.njk, src/views/evidence-removal.njk, src/views/evidence-upload.njk
https://companieshouse.atlassian.net/browse/LFA-1385
Added back buttons to document upload screens
```
```
- types other than `fix:` and `feat:` are allowed, for …
=> feat: add back button to upload screens

src/controllers/EvidenceQuestionController.ts, src/controllers/OtherReasonController.ts, src/views/evidence-upload.njk, test/controllers/EvidenceQuestionController.test.ts, test/controllers/OtherReasonController.test.ts
https://companieshouse.atlassian.net/browse/LFA-1280
Using "Continue" on "Do you want to add documents..." screen, if no validation messages were shown and the user selected “No”, takes the user to the check-answers screen.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic …
=> Feature: add transition to and from evidence question page

package-lock.json, src/middleware/LoadAppealMiddleware.ts, src/models/PenaltyIdentifier.schema.ts, src/modules/appeals-service/AppealsService.ts, src/modules/appeals-service/errors.ts, test/middleware/LoadAppealMiddleware.test.ts, test/models/AppDataFactory.ts
Part of https://companieshouse.atlassian.net/browse/LFA-1467
Added the middleware and tests.
```
``` …
=> feat: added middleware to load appeal from mongo

src/controllers/EvidenceQuestionController.ts
https://companieshouse.atlassian.net/browse/LFA-1385
Put back accidentally updated transition to other reason uri from evidence upload question page
```
```
- types …
=> fix: update previous navigation on evidence question controller

.env.vagrant, src/controllers/EvidenceUploadController.ts, test/controllers/EvidenceUploadController.test.ts
https://companieshouse.atlassian.net/browse/LFA-1625
```
``` …
=> feature: add gif, xlsx and zip file support

.env.vagrant
handle zip files in the ways we can, by checking for:
```
application/zip
application/x-zip-compressed
application/x-zip
multipart/x-zip
```
and then if the zip file still cannot be identified in older operating systems or older versions of browsers:
`application/octet-stream`
then the transfer file API handles it accordingly
```
```
- BREAKING CHANGE: a commit …
=> add zip file mime types

src/controllers/PenaltyDetailsController.ts, src/utils/PenaltyReferenceSanitizer.ts
=> Fix: lowercase legacy numbers

src/controllers/BaseController.ts, src/controllers/EvidenceUploadController.ts
https://companieshouse.atlassian.net/browse/LFA-1726
Added navigation permissions when error page is rendered.
```
``` …
=> fix: bug with continue without upload button

package-lock.json, package.json, src/controllers/BaseController.ts, src/controllers/CheckYourAppealController.ts, src/controllers/ConfirmationController.ts, src/controllers/EvidenceQuestionController.ts, src/controllers/EvidenceRemovalController.ts, src/controllers/EvidenceUploadController.ts, src/controllers/SafeNavigationBaseController.ts, src/controllers/processors/AppealStorageFormActionProcessor.ts, src/controllers/processors/InternalEmailFormActionProcessor.ts, src/controllers/processors/UserEmailFormActionProcessor.ts, src/middleware/AuthMiddleware.ts, src/middleware/FileRestrictionsMiddleware.ts, src/middleware/LoadAppealMiddleware.ts, test/ApplicationFactory.ts, test/controllers/BaseController.test.ts, test/controllers/EvidenceDownloadController.test.ts, test/controllers/SafeNavigationBaseController.test.ts, test/controllers/processors/AppealStorageFormSubmissionProcessor.test.ts, test/controllers/processors/InternalEmailFormSubmissionProcessor.test.ts, test/controllers/processors/UserEmailFormSubmissionProcessor.test.ts, test/middleware/AuthMiddleware.test.ts, test/middleware/FileRestrictionsMiddleware.test.ts, test/middleware/LoadAppealMiddleware.test.ts, test/utils/session/SessionFactory.ts
https://companieshouse.atlassian.net/browse/LFA-1680
```
``` …
=> fix: upgrade web application to node-session-handler v2.0

src/views/penalty-details.njk
https://companieshouse.atlassian.net/browse/BI-3330
```
``` …
=> feat: update penalty details page with legacy help

src/views/other-reason.njk, test/controllers/OtherReasonController.test.ts
https://companieshouse.atlassian.net/browse/BI-3374
Added hint to other reason screen
```
``` …
=> feat: added hint to other reason page

package-lock.json, package.json, src/ContainerFactory.ts, src/modules/Types.ts
N/A
Added standardised way to access the companies house node sdk using DI.
```
``` …
=> refactor: added companies house sdk in a standardised manner

src/controllers/processors/UserEmailFormActionProcessor.ts, test/controllers/processors/UserEmailFormSubmissionProcessor.test.ts
https://companieshouse.atlassian.net/browse/LFA-1655
Add 'Type' row for penalty reference number to customer emails
```
``` …
=> feat: add penalty reference to customer email builder

src/modules/Types.ts
N/A
Hotfix change as TS does not support type to value inference
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, …
=> hotfix: fixed undefined issue in auth types

src/controllers/processors/UserEmailFormActionProcessor.ts, test/controllers/processors/UserEmailFormSubmissionProcessor.test.ts
https://companieshouse.atlassian.net/browse/LFA-1658
Notifications API PR: https://github.com/companieshouse/chs-notification-api/pull/147
```
``` …
=> feature: add company name into confirmation email

src/controllers/processors/InternalEmailFormActionProcessor.ts, test/controllers/processors/InternalEmailFormSubmissionProcessor.test.ts
https://companieshouse.atlassian.net/browse/LFA-1659
Notifications API: https://github.com/companieshouse/chs-notification-api/pull/148
```
``` …
=> feat: add company name in internal email

src/controllers/OtherReasonController.ts
N/A
other-reason back button was taking user to review appeal page, it should take user back to disclaimer page instead
```
```
- types other than `fix:` and `feat:` …
=> bugfix: point 'other-reason' back button to disclaimer page

src/views/review-penalty.njk
=> fix: removed hidden text on penalty summary screen

src/controllers/processors/AppealStorageFormActionProcessor.ts, src/models/CreatedBy.ts, test/controllers/processors/AppealStorageFormSubmissionProcessor.test.ts
https://companieshouse.atlassian.net/browse/LFA-1594
Added email address to the Appeal object for when we submit an appeal. This is required for creating a new contact in CHIPS.
```
``` …
=> feat: add email address to appeal on submission

src/controllers/AccessibilityStatementController.ts, src/controllers/index.ts, src/utils/Paths.ts, src/views/accessibility-statement.njk, src/views/layout.njk, test/controllers/AccessibilityStatementController.test.ts
https://companieshouse.atlassian.net/browse/LFA-1607
Adds accessibility statement
```
``` …
=> feat: add accessibility statement

src/views/other-reason-disclaimer.njk
https://companieshouse.atlassian.net/browse/LFA-1796
Update content on disclaimer page
```
``` …
=> feat: update content on disclaimer page

.env.vagrant, src/middleware/ErrorHandler.ts, src/views/error-not-found.njk, test/middleware/ErrorHandler.test.ts
https://companieshouse.atlassian.net/browse/LFA-1470
```
``` …
=> feat: add not found page

src/ContainerFactory.ts
=> fix: rebel1 down due to missing enviroment variable

src/controllers/validators/DateValidator.ts, test/models/chunks/DateSchema.test.ts
Example of dates that should be invalid:
31st of Feb
30th of Feb
31st of April
```
``` …
=> fix: calendar invalid dates should trigger validation error

src/controllers/IllPersonController.ts, src/controllers/IllnessStartDateController.ts, src/views/illness/ill-person.njk, test/controllers/IllPersonController.test.ts
https://companieshouse.atlassian.net/browse/LFA-1443
```
``` …
=> add: transition functionality from Who is Ill page

src/views/illness/illness-start-date.njk
=> fix: heading size for Illness Start Date

package-lock.json, package.json
removed all high vulnerabilities and most low.
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, `style:`, …
=> fix: high severity vulnerabilities

src/views/confirmation.njk, src/views/landing.njk
https://companieshouse.atlassian.net/browse/LFA-1936
```
``` …
=> feat: Add Late Filling Penalty Guidance and link 

.dockerignore, Dockerfile, README.md, Tiltfile.dev
=> chore: rewrite Dockerfile to use base image

package-lock.json, package.json
=> Upgrade node-jose to solve vulnerability issue

src/utils/ExpressConfigFunctionFactory.ts
Resolves an issue at: [BI-6939](https://companieshouse.atlassian.net/browse/BI-6939)
Add app.locals.chs that was missing and was not picking up the CHS_URL
```
``` …
=> Add app.locals.chs that was missing and was not picking up the CHS_URL

package-lock.json, package.json
Resolves: [BI-7012](https://companieshouse.atlassian.net/browse/BI-7012)
Upgrading axios to 0.21.1 resolving a high risk vulnerability issue
```
```
- types other …
=> Upgrading axios to 0.21.1 resolving a high risk vulnerability issue

src/views/other-reason.njk, test/controllers/OtherReasonController.test.ts
Resolves [BI-7982](https://companieshouse.atlassian.net/browse/BI-7982)
Changing hint text on 'Other reason' journey on Appeals service
```
``` …
=> Changing hint text on 'Other reason' journey on Appeals service

src/controllers/IllnessFurtherInformationController.ts, src/utils/Paths.ts, src/views/illness/illness-information.njk
Resolves BI-8254(https://companieshouse.atlassian.net/browse/BI-8254)
Changing incorrect url usage from illness/further-information to match user story URL as stipulated  illness/illness-information
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING …
=> fix: Changing incorrect url usage

gulpfile.js, package-lock.json, package.json
Resolves [BI-8190](https://companieshouse.atlassian.net/browse/BI-8190)
- Remove unused `node-sass` library and related,
- Remove unused dependency `hosted-git-info`
- Updated `gulpfile` by removing not necessary tasks
- Update transitive dependency of `nunjucks` (glob-parent --depth 4)
- Update transitive dependency of `gulp-nodemon` (npm update normalize-url --depth 8)
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates with MINOR in …
=> Remove unused node-sass library and related, and update gulpfile

src/views/landing.njk
Resolves [BI-8631](https://companieshouse.atlassian.net/browse/BI-8631)
Adding inset text to screen to advise users that they can only submit one appeal per penalty
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits of …
=> Adding inset text to screen to advise users about appeal

src/views/choose-appeal-reason.njk
Resolves [BI-8573](https://companieshouse.atlassian.net/browse/BI-8573)
Adding correct validation message for error text box that appears when user presses 'continue' without selecting a reason. 
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING …
=> Adding correct validation message for the error text box

src/views/illness/illness-information.njk
Resolves [BI-8641](https://companieshouse.atlassian.net/browse/BI-8641)
Fixing grammatical mistakes on how did this affect your ability to file page that was picked up in test. 
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part …
=> Updating detail text to fix grammatical mistake

src/models/PenaltyIdentifierSchemaFactory.ts, src/views/penalty-details.njk, test/controllers/PenaltyDetailsController.test.ts, test/models/PenaltyIdentifierSchemaFactory.test.ts
Resolves [BI-8741](https://companieshouse.atlassian.net/browse/BI-8741)
Updating error message on the 'what are the penalty details' page to be consistent with the rest of the journey.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be …
=> Updating validation text for 'what are the penalty details page'

src/views/illness/ill-person.njk
Resolves: [BI-8733](https://companieshouse.atlassian.net/browse/BI-8733)
Updating error message for validation on 'who was ill' page
```
``` …
=> Updating error message for validation on 'who was ill' page

src/controllers/validators/PenaltyDetailsValidator.ts
Resolves: [BI-8741](https://companieshouse.atlassian.net/browse/BI-8741)
Adding further amendments to enter your penalty details page to cover all error validation scenarios
```
``` …
=> Further amendments to validation error messages on penalty details page

src/models/CreatedBy.ts
https://companieshouse.atlassian.net/browse/BI-8639
Added name field to createdBy Model
```
``` …
=> Added Name to createdby model

src/controllers/OtherReasonController.ts, src/models/OtherReason.schema.ts, src/views/other-reason.njk, test/controllers/OtherReasonController.test.ts, test/models/OtherReasonSchema.test.ts
Resolves [BI-8731](https://companieshouse.atlassian.net/browse/BI-8731)
Add name field into other reason journey and update tests
```
``` …
=> Add name field into other reason journey and update tests

src/controllers/CheckYourAppealController.ts, src/views/check-your-appeal.njk, test/controllers/CheckYourAppealController.test.ts
https://companieshouse.atlassian.net/browse/BI-8535
Added Illness Reason to show on "Check Your Appeal" screen + unit tests
```
``` …
=> Add illness reason to check appeal page

src/views/check-your-appeal.njk
Part of [BI-8535](https://companieshouse.atlassian.net/browse/BI-8535)
Add text type reason to check appeal page
```
``` …
=> Add text type reason to check appeal page

src/controllers/processors/InternalEmailFormActionProcessor.ts, src/utils/appeal/extra.data.ts, test/controllers/processors/InternalEmailFormSubmissionProcessor.test.ts
Resolves part of [BI-8536](https://companieshouse.atlassian.net/browse/BI-8536)
Add illness reason to internal email
```
```
- types other than `fix:` and `feat:` …
=> Add illness reason to internal email

src/controllers/CheckYourAppealController.ts, src/controllers/processors/InternalEmailFormActionProcessor.ts, src/utils/appeal/extra.data.ts, src/views/check-your-appeal.njk, test/controllers/CheckYourAppealController.test.ts, test/controllers/processors/InternalEmailFormSubmissionProcessor.test.ts, test/utils/appeal/extra.data.test.ts
Part of [BI-8535](https://companieshouse.atlassian.net/browse/BI-8535)
Part of [BI-8536](https://companieshouse.atlassian.net/browse/BI-8536)
Fix ill person name on someone else option 
Fix date format on Illness start date
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in …
=> Fix illperson name on someone else option and date format

src/controllers/processors/InternalEmailFormActionProcessor.ts, test/controllers/processors/InternalEmailFormSubmissionProcessor.test.ts
Resolve [BI-8832](https://companieshouse.atlassian.net/browse/BI-8832)
Add name field to other reason object for the lfp appeal internal email template
```
```
- …
=> Add name field to other reason object the lfp email template

src/views/check-your-appeal.njk
Resolves: [BI-8792](https://companieshouse.atlassian.net/browse/BI-8792)
Add name field to 'Check your appeal' page for Other reason
```
``` …
=> Add name field to 'Check your appeal' page for Other reason

src/views/check-your-appeal.njk
Resolves [BI-8792](https://companieshouse.atlassian.net/browse/BI-8792)
Change order of Your Name field based on the prototype
```
``` …
=> Change order of Your Name field based on the prototype

src/controllers/EvidenceQuestionController.ts, src/controllers/IllPersonController.ts, src/controllers/OtherReasonController.ts, src/views/evidence-question.njk, test/controllers/EvidenceQuestionController.test.ts, test/controllers/IllPersonController.test.ts, test/controllers/OtherReasonController.test.ts
Resolve [BI-8817](https://companieshouse.atlassian.net/browse/BI-8817)
Add visualization on radio button selection in upload evidence page
```
```
- types other …
=> Add visualization on radio button selection in upload evidence page

src/controllers/OtherReasonDisclaimerController.ts
Resolves [BI-8834](https://companieshouse.atlassian.net/browse/BI-8834)
Add dynamic back navigation from other reason disclaimer page based on `illnessReasonEnabled` flag
```
``` …
=> Add dynamic back navigation from other reason disclaimer page

src/controllers/CheckYourAppealController.ts, src/controllers/ChooseAppealReasonController.ts, src/controllers/ConfirmationController.ts, src/controllers/ContinuedIllnessController.ts, src/controllers/IllPersonController.ts, src/controllers/IllnessFurtherInformationController.ts, src/controllers/IllnessStartDateController.ts, src/controllers/OtherReasonController.ts, src/controllers/PenaltyDetailsController.ts, src/middleware/Logger.ts, test/middleware/logger.test.ts
Resolves: [BI-8806](https://companieshouse.atlassian.net/browse/BI-8806)
Fix the logging message for failed appeals in FrontEnd
```
``` …
=> Fix the logging message for failed appeals in FrontEnd

src/controllers/OtherReasonController.ts, src/models/CreatedBy.ts, src/models/OtherReason.schema.ts, src/views/other-reason.njk, test/controllers/OtherReasonController.test.ts
Resolves: [BI-8811](https://companieshouse.atlassian.net/browse/BI-8811)
Add relationship to company field to Other Reason journey - Web
```
``` …
=> Add relationship to company field to Other Reason journey - Web

src/models/OtherReason.schema.ts, src/views/other-reason.njk, test/controllers/OtherReasonController.test.ts, test/models/OtherReasonSchema.test.ts
Resolving: [BI-8744](https://companieshouse.atlassian.net/browse/BI-8744)
Add validation to other reasons tell us why you're appealing page
```
```
- types other …
=> Add validation to other reasons tell us why you're appealing page

src/modules/appeals-service/AppealsService.ts, test/modules/appeals-service/AppealsService.test.ts
Part of [BI-8806](https://companieshouse.atlassian.net/browse/BI-8806)
Improve logging message for failed appeals
```
``` …
=> Improve logging message for failed appeals

src/views/other-reason.njk, test/controllers/OtherReasonController.test.ts
Fixes: [BI-8744](https://companieshouse.atlassian.net/browse/BI-8744)
Fix validation message to other reasons 'tell us why you're appealing' page
```
```
- types …
=> Fix validation message to other reasons 'tell us why you're appealing' page

src/views/evidence-upload.njk
Resolves: https://companieshouse.atlassian.net/browse/BI-8702
Amended text on Upload a Document screen when user tries to upload more than one document.
```
```
- …
=> Updated text on upload document page

src/modules/appeals-service/AppealsService.ts, test/modules/appeals-service/AppealsService.test.ts
Part of [BI-8806](https://companieshouse.atlassian.net/browse/BI-8806)
Fix logging message for failed appeals
```
``` …
=> Fix logging message for failed appeals

src/views/evidence-question.njk
Resolves: https://companieshouse.atlassian.net/browse/BI-8935
Amended Text on Evidence Question screen to use the word Upload instead of Add 
```
```
- types other …
=> Amended text on evidence question screen

src/controllers/processors/InternalEmailFormActionProcessor.ts, test/controllers/processors/InternalEmailFormSubmissionProcessor.test.ts
https://companieshouse.atlassian.net/browse/BI-8813
Add field relationshipToCompany to return record for Other reason.
Update unit test with relationshipToCompany field.
```
``` …
=> Add relationship to company to internal email

src/views/confirmation.njk, src/views/layout.njk
https://companieshouse.atlassian.net/browse/BI-8917
Updated Feedback link on beta banner and Confirmation page to point to new Smart Survey link
```
```
- types …
=> Updated feedback link on banner + confirmation

src/controllers/EvidenceUploadController.ts, src/views/evidence-upload.njk, test/controllers/EvidenceUploadController.test.ts
https://companieshouse.atlassian.net/browse/BI-8702
Update the upload evidence page and replace Add a document label to Upload a document
Update Add document button to Upload document
Update Continue without adding a document to Continue without uploading a document
Update error message to You must upload a document or click "Continue without uploading documents"
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates with MINOR in semantic …
=> Update references of add a document to upload a document

src/views/evidence-question.njk, test/controllers/EvidenceQuestionController.test.ts
Resolves:[BI-8992](https://companieshouse.atlassian.net/browse/BI-8992)
Rename tab text for 'Do you want to add documents to support your application?' page
```
``` …
=> Rename tab text for 'Do you want to add documents to support your application?' page

src/utils/Paths.ts, src/views/illness/illness-end-date.njk
Resolves: [BI-8949](https://companieshouse.atlassian.net/browse/BI-8949)
Create skeleton template for 'When did your illness end?' screen
```
```
- types other …
=> Create skeleton template for 'When did your illness end?' screen

src/controllers/ContinuedIllnessController.ts, src/models/Illness.ts, test/controllers/CheckYourAppealController.test.ts, test/controllers/processors/InternalEmailFormSubmissionProcessor.test.ts, test/utils/appeal/extra.data.test.ts
Resolve [BI-9078](https://companieshouse.atlassian.net/browse/BI-9078)
Change data format for continued illness object to boolean
```
``` …
=> Change data format for continued illness object

src/controllers/ContinuedIllnessController.ts, src/views/illness/continued-illness.njk
Resolve [BI-9077](https://companieshouse.atlassian.net/browse/BI-9077)
Add which option was selected on is the person still ill page
```
``` …
=> Add which option was selected on is the person still ill page

src/controllers/IllnessFurtherInformationController.ts, src/utils/appeal/extra.data.ts, test/controllers/IllnessFurtherInformationController.test.ts, test/utils/appeal/extra.data.test.ts
Resolves [BI-9065](https://companieshouse.atlassian.net/browse/BI-9065)
Add dynamic back redirection to illness information page
```
``` …
=> Add dynamic back redirection to illness information page

src/controllers/IllnessEndDateController.ts, src/views/illness/illness-end-date.njk, test/controllers/IllnessEndDateController.test.ts
Resolves: [BI-8957](https://companieshouse.atlassian.net/browse/BI-8957)
Add dynamic hint text to the 'When did the illness end?' page
```
``` …
=> Add dynamic hint text to the 'When did the illness end?' page

src/controllers/CheckYourAppealController.ts, src/views/check-your-appeal.njk, test/controllers/CheckYourAppealController.test.ts
[BI-8959](https://companieshouse.atlassian.net/browse/BI-8959)
Add illnessEndDate const in the prepareViewModelFromSession function of CheckYourAppealController.
Add section to check-your-appeal.njk to display the illnessEndDate if it is not null
Updated unit test descriptions and added new test to check that illnessEndDate is returned
```
```
- BREAKING CHANGE: …
=> Add end date to check appeal page

src/controllers/validators/IllnessEndDateValidator.ts
[BI-8946](https://companieshouse.atlassian.net/browse/BI-8946)
Jamie Jones raised an issue where if the year field was blank the correct error 'You must enter a year' was displayed but also the error 'End date must be after the start date'. After calling the super class, DateValidator, this would find the year empty error and the IllnessEndDateValidator would then still try and validate if end date was before start date as the end date year is set to 2001 when the date fields are extracted from the body even though the year is empty!
Added a check that if there are no validation errors returned from the DateValidator only then validate if the end date is before the start date.
We are committed to keeping commit history clean, consistent and linear. To achieve this commit should be …
=> Only validate end date before start date when no other errors

src/controllers/processors/InternalEmailFormActionProcessor.ts, test/controllers/processors/InternalEmailFormSubmissionProcessor.test.ts
Resolves [BI-8960](https://companieshouse.atlassian.net/browse/BI-8960)
Add illness-end-date to appeals Internal Email
=> Add illness-end-date to appeals Internal Email

src/views/layout.njk
Resolves: https://companieshouse.atlassian.net/browse/BI-8740
Added favicon to service to show on internet browser tabs 
```
``` …
=> Added favicon to service

src/views/evidence-upload.njk
https://companieshouse.atlassian.net/browse/BI-9228
Added help text to upload document screen for previously uploaded documents. Reminding users to delete if they want to. 
```
``` …
=> Added hint text to upload document screen

src/views/penalty-details.njk
https://companieshouse.atlassian.net/browse/BI-9418
Amended help text for penalty details screen to show correct length of penalty reference numbers 
```
```
- …
=> amend help text for penalty details screen

package-lock.json, package.json
https://companieshouse.atlassian.net/browse/BI-10013
Note that glob-parent and yargs-parser cannot be updated due to Gulp relying on them, which is a deprecated library. We should refactor in the future to remove Gulp from this repo to avoid these security issues.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API …
=> Fix dependabot alerts

src/views/confirmation.njk
Resolves [BI-11379](https://companieshouse.atlassian.net/browse/BI-11379)
Amending smart-survey link on confirmation page to redirect to the correct link. 
```
``` …
=> Update smart survey link to the correct version on confirmation page

src/views/layout.njk
Resolves [BI-11381](https://companieshouse.atlassian.net/browse/BI-11381)
Updating survey link located on the service' s feedback banner, to redirect to the correct smart survey URL  
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be …
=> Updating survey link for feedback link on web service layout template

src/views/evidence-removal.njk, src/views/illness/continued-illness.njk, src/views/illness/illness-end-date.njk, src/views/review-penalty.njk, src/views/select-the-penalty.njk
[BI-11763](https://companieshouse.atlassian.net/browse/BI-11763)
Amended the spacing between the back button and page title for these pages:
- Select the penalty 
- Review the penalty
- Is the person still ill
- When did the illness end
- Evidence removal
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change …
=> fix spacing between back button and page title

src/views/accessibility-statement.njk
https://companieshouse.atlassian.net/browse/BI-12050
Text change on the accessibility statement screen
```
```
- types other than `fix:` and `feat:` are allowed, …
=> updated accessibility statement text

src/views/evidence-upload.njk
https://companieshouse.atlassian.net/browse/BI-11410
Added additional guidance to the document upload page so that it now also covers do not upload criteria 
```
``` …
=> added do not upload criteria to document upload page

src/views/accessibility-statement.njk, src/views/check-your-appeal.njk, src/views/choose-appeal-reason.njk, src/views/download-file.njk, src/views/error-custom.njk, src/views/error-not-found.njk, src/views/error.njk, src/views/evidence-question.njk, src/views/evidence-upload.njk, src/views/illness/continued-illness.njk, src/views/illness/ill-person.njk, src/views/illness/illness-end-date.njk, src/views/illness/illness-information.njk, src/views/illness/illness-start-date.njk, src/views/landing.njk, src/views/other-reason-disclaimer.njk, src/views/other-reason.njk, src/views/penalty-details.njk, src/views/review-penalty.njk, src/views/select-the-penalty.njk, src/views/signout.njk
https://companieshouse.atlassian.net/browse/BI-12198
Add IDs to the page titles in the LFP Appeals service
```
``` …
=> added ids to page titles

src/views/confirmation.njk, src/views/evidence-removal.njk
https://companieshouse.atlassian.net/browse/BI-12198
```
``` …
=> added ids to confirmation and evidence removal pages

src/views/evidence-upload.njk
https://companieshouse.atlassian.net/browse/BI-12168
Removed unnecessary text on evidence upload screen
```
```
- types other than `fix:` and `feat:` are allowed, …
=> remove unneeded text on evidence screen

package-lock.json
=> low vulnerability fix

src/middleware/AuthMiddleware.ts
Remove unnecessary env var and make it consistent with other services
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, …
=> Remove unnecessary env var

README.md
https://companieshouse.atlassian.net/browse/IE-302
Fix readme so that it will trigger a release pipeline to test dependency track pipeline changes
=> IE-302: minor docs update to test change to concourse pipeline
