companieshouse/lfp-appeals-frontend

package-lock.json
package.json

Dependency was highlighted as vulnerable. When I looked into it it became apparent that dependency is not used and can be removed.

build: remove deprecated and unused gulp-util dependency

---

package-lock.json
package.json

None
Add 'tslib' as explicit dependency since 'tslib' is used by decorators.
See 'tslib_1.__decorate' in example below:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
const inversify_express_utils_1 = require("inversify-express-utils");
let LandingController = class LandingController {
renderView(req, res, next) {
res.render('landing');
}
};
tslib_1.__decorate([
inversify_express_utils_1.httpGet(''),
tslib_1.__metadata("design:type", Function),
tslib_1.__metadata("design:paramtypes", [Object, Object, Function]),
tslib_1.__metadata("design:returntype", void 0)
], LandingController.prototype, "renderView", null);
LandingController = tslib_1.__decorate([
inversify_express_utils_1.controller('/')
], LandingController); …
```

chore: add 'tslib' as explicit dependency

---

src/utils/ConfigLoader.ts

None
Loads templates from build directory instead of loading it from source directory. Source directory is not present in released artefact which makes application to crash.
```
``` …

fix: make application load templates from build directory

---

src/utils/validation/ValidationError.ts
src/views/penalty-details.njk
test/utils/validation/ValidationError.test.ts

None
Converts camel cased field names into hyphen separated words when building error href
```
``` …

improvement: separate words with hyphens when building error link

---

src/controllers/EntryController.ts
src/controllers/HealthCheckController.ts
src/controllers/LandingController.ts
src/controllers/PenaltyDetailsController.ts
src/public/sass/application.scss
src/utils/ConfigLoader.ts
src/utils/Paths.ts
src/views/layout.njk
test/controllers/EntryController.test.ts
test/controllers/HealthCheckController.test.ts
test/controllers/PenaltyDetailsController.test.ts

None
Serve application from '/appeal-a-penalty' path.
Note: It does not use internal CDN at this point. It needs to be explored further and introduced later if needed.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits of …

refactor: serve application from '/appeal-a-penalty' path

---

src/views/landing.njk
src/views/layout.njk
src/views/other-reason-disclaimer.njk
src/views/other-reason.njk
src/views/penalty-details.njk

N/A
Substitute double for single quotation and remove feedback banner from disclaimer page (different ticket handles that)
```
``` …

refactor: substitute double for single quotation in templates

---

src/controllers/PenaltyDetailsController.ts

NO JIRA
Converted penalty reference to uppercase on penalty details submission
```
``` …

fix: make penalty reference uppercase before saving to session

---

.mocharc.json
test/ApplicationFactory.ts
test/controllers/BaseController.test.ts
test/controllers/EvidenceRemovalController.test.ts
test/controllers/SafeNavigationBaseController.test.ts
test/controllers/processors/InternalEmailFormSubmissionProcessor.test.ts
test/middleware/FileTransferFeatureMiddleware.test.ts

None
In nutshell it loads env variables from `.env.local` in single place (when mocha framework loads itself) for any test so there is no longer need to manually load config in every test file. As a consequence it is much easier to run single test in IDE
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change …

refactor: load test environment variables in one place

---

src/controllers/EvidenceUploadController.ts
test/controllers/EvidenceUploadController.test.ts

N/A
Requested by Richard:
- Basically, what I am seeing is the double quotes surrounding continue without adding documents are 66s (“) & 99s (”) for ours, whereas for Extensions, they are "
- but they are reporting as non-asscii characters. That would suggest that in older browsers, they may not render correctly
```
```
- BREAKING CHANGE: a commit that has a …

Fix: update error message double quotes

---

src/controllers/EvidenceUploadController.ts
src/views/evidence-upload.njk
test/controllers/EvidenceUploadController.test.ts

https://companieshouse.atlassian.net/browse/LFA-1280
Using "Continue without adding documents" on "Add documents..." screen, takes the user to the check-answers screen.
If JavaScript is disabled, this does not save the file selected in the file browser.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change …

feat: add continue without evidence transition

---

src/ApplicationFactory.ts
src/Constants.ts
src/ContainerFactory.ts
src/middleware/Logger.ts
src/utils/ConfigLoader.ts
src/utils/ExpressConfigFunctionFactory.ts
test/middleware/ErrorHandler.test.ts
test/utils/ConfigLoader.test.ts

None
With this change application won't throw an error when configuration profile file is missing. In that case, cause file does not exist, environment variables won't be loaded and application will fail later during launch phase only if required configuration is missing.
I used an occasion to cleanup code and restore correct responsibilities split.
```
```
- …

feat: make configuration profiles optional

---

src/controllers/processors/InternalEmailFormActionProcessor.ts
test/controllers/processors/InternalEmailFormSubmissionProcessor.test.ts

https://companieshouse.atlassian.net/browse/LFA-1656
Add 'Type' row for penalty reference number to internal emails
```
``` …

feat: add penalty reference to internal email builder

---

src/controllers/validators/PenaltyDetailsValidator.ts
test/controllers/PenaltyDetailsController.test.ts

N/A
Fixed bug where validation errors in the details screen wouldn't both show up when the service failed to get the late filling penalties from the api.
```
```
- …

fix: fixed validation errors not showing when failing to get penalties

---

src/controllers/BaseController.ts
src/controllers/PenaltyDetailsController.ts
src/controllers/ReviewPenaltyController.ts
test/controllers/PenaltyDetailsController.test.ts
test/utils/validation/PenaltyDetailsValidator.test.ts

N/A
A bug was spotted where a user would input an old penalty reference and if the company had only one penalty list, it would fail because we weren't replacing the penaltyReference field correctly.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING …

fix: fixed bug when using old pr on company with 1 penalty

---

src/controllers/EvidenceUploadController.ts
src/controllers/processors/InternalEmailFormActionProcessor.ts
src/models/Attachment.ts
test/controllers/EvidenceUploadController.test.ts
test/controllers/processors/InternalEmailFormSubmissionProcessor.test.ts
test/models/AppDataFactory.ts

https://companieshouse.atlassian.net/browse/LFA-1595
* Added additional property `url` to `Attachment` object
* After file upload, attachment url is saved to the session
* Updated `InternalEmailFormActionProcessor.ts` to use attachment url in session when generating email body
* Appeal ID will be appended to the attachment url (for enabling download permissions) after appeal entry is stored in Mongo Db (requires change in Appeals API - follow up PR)
```
```
- feat: a commit …

feat: add prompt download url to attachment object

---

src/controllers/CheckYourAppealController.ts
src/controllers/ConfirmationController.ts
src/controllers/processors/SessionCleanupProcessor.ts
src/models/ApplicationData.ts
test/controllers/CheckYourAppealController.test.ts
test/controllers/ConfirmationController.test.ts

https://companieshouse.atlassian.net/browse/LFA-1641
After checking the penalty details the user is not able to go back to change them. The only permitted route is to go back to the beginning to the journey by pressing the govuk icon.
**Note:** The user can still access the confirmation screen 
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING …

feat: session cleanup after submission

---

src/middleware/CompanyAuthMiddleware.ts
test/controllers/EvidenceUploadController.test.ts
test/middleware/CompanyAuthMiddleware.test.ts

https://companieshouse.atlassian.net/browse/LFA-1295
On the CompanyAuthMiddleware, which is applied to most pages in the journey, added a redirect to the penalty details page when there is no appeal data in the session
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic …

fix: CompanyAuthMiddleware - add redirect to penalty details page when no appeal in session

---

src/views/choose-appeal-reason.njk

https://companieshouse.atlassian.net/browse/LFA-1900
Adds the govuk-spec Error Banner to the Choose Reason page. Thanks to @richardetherington for spotting.
```
``` …

fix: Add error banner to Choose Reason page

---

src/controllers/IllnessStartDateController.ts
test/controllers/IllnessStartDateController.test.ts

When the page is reloaded after you enter a date, the field is prepopulated with the session as it should ... except that:
for some months, the value of the day, is decremented by one.I dont think this is a problem about how we save the date to session, I think its to do with how we read it.
most likely linked to how new Date() works.
```
```
- BREAKING CHANGE: a …

bugfix: illness start date session reading bug

---

src/modules/nunjucks/DateFilter.ts
test/modules/nunjucks/DateFilter.test.ts

https://companieshouse.atlassian.net/browse/LFA-1440
Update to the custom date filter for Nunjucks, which expected a month value between 0-11 instead of 1-12 (due to previous use of Date type instead of string). Added unit test cases to cover these scenarios.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API …

fix: Off-By-One bug in Nunjucks Date filter

---

README.md
Tiltfile.dev

None
Docker releases >=2.4.0.0 have BuildKit enabled by default - this breaks image builds due to a known issue (https://github.com/moby/buildkit/issues/816) with BuildKit and ONBUILD COPY --from directives which we use in our runtime image.
Prefixing `docker build` commands with `DOCKER_BUILDKIT=0` fixes the issue
```
```
- BREAKING CHANGE: a commit that has a …

Use DOCKER_BUILDKIT=0 flag for Docker builds

---

package-lock.json
package.json

Resolves: [BI-7937](https://companieshouse.atlassian.net/browse/BI-7937)
Update hosted-git-info dependency to a newer version (2.8.9) to resolve the security vulnerability reported by dependabot
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING …

Update hosted-git-info dependency to resolve the security vulnerability

---

package-lock.json

Resolves: [BI-7861](https://companieshouse.atlassian.net/browse/BI-7861)
Upgrade lodash to 4.17.21 to fix security vulnerability reported by dependabot
```
```
- …

Upgrade lodash to 4.17.21 to fix security vulnerability

---

package-lock.json
package.json

Resolves: [BI-7898](https://companieshouse.atlassian.net/browse/BI-7898)
Update merge dependency to 2.1.1 to resolve security vulnerability reported by dependabot
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits of …

Update merge dependency to 2.1.1 to resolve security vulnerability

---

src/controllers/EvidenceRemovalController.ts
src/controllers/EvidenceUploadController.ts
src/controllers/IllPersonController.ts
src/controllers/OtherReasonController.ts
src/controllers/processors/InternalEmailFormActionProcessor.ts
src/models/Illness.ts
src/models/Reasons.ts
test/controllers/CheckYourAppealController.test.ts
test/controllers/processors/InternalEmailFormSubmissionProcessor.test.ts

Part of [BI-8248](https://companieshouse.atlassian.net/browse/BI-8248) 
Add either/or type logic on reasons and reinforce type-checking to Generalise Appeals Reason Object
```
``` …

Add either/or type logic on reasons obj and reinforce type-checking

---

src/views/illness/illness-end-date.njk

Resolves [BI-8950](https://companieshouse.atlassian.net/browse/BI-8950)
Adding Matomo event to be tracked when clicking continue button on when did illness end page
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits of …

Adding Matomo event when clicking continue button on illness end date page

---

src/controllers/IllnessEndDateController.ts
test/controllers/IllnessEndDateController.test.ts
test/utils/appeal/extra.data.test.ts

[BI-8948](https://companieshouse.atlassian.net/browse/BI-8948)
Add logic to store the illness end date in the session.
Update function prepareViewModelFromAppeal to check if illnessEnd value is set and if so split it out in to day, month and year and return
Update function prepareSessionModelPriorSave to set the illnessEnd value onto the session value
Add unit tests for new functionality
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates …

Add illness end date logic

---

src/controllers/IllnessEndDateController.ts
src/controllers/validators/IllnessEndDateValidator.ts
src/models/fields/Date.schema.ts
test/controllers/IllnessEndDateController.test.ts
test/controllers/IllnessStartDateController.test.ts
test/models/chunks/DateSchema.test.ts
test/utils/validation/IllnessEndDateValidator.test.ts

[BI-8946](https://companieshouse.atlassian.net/browse/BI-8946)
Create new validator class IllnessEndDateValidator. This extends DateValidator and includes functionality to check whether the end date is before the start date.
Update IllnessEndDateController to use new validator class, IllnessEndDateValidator.
Update start date in future error message to date in future error message to make now generic
```
```
- feat: a commit that introduces a new feature to the codebase (this …

Add validation to illness end date

---

src/views/evidence-upload.njk

Resolves [BI-9126](https://companieshouse.atlassian.net/browse/BI-9126)
Removing the 'continue without uploading documents' link on 'upload your evidence page'
```
``` …

Removing 'continue without uploading documents' link 

---

src/controllers/IllnessEndDateController.ts
src/models/fields/Date.schema.ts
src/views/illness/illness-end-date.njk
test/controllers/IllnessEndDateController.test.ts

[BI-9140](https://companieshouse.atlassian.net/browse/BI-9140)
Add hidden govukInput field to illness-end-date.njk and update the hint text to be consistant with how its been done for the continued illness page.
Add optional field to the Date.schema.ts file. This has been added as an effect of having the hidden input field to store the hint text.
Update IllnessEndDateController to only send the illness start date rather than a formatted string.
```
```
- feat: a commit that …

Fix issue with hint not displaying on illness end date when errors

---

src/views/penalty-details.njk

Resolves [BI-9239)](https://companieshouse.atlassian.net/browse/BI-9239)
Amending help text on the 'What are the penalty details?' screen to explain in a clearer way what the user needs to enter as a reference number / penalty reference.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with …

Amending help text on 'what are the penalty details page'

---

src/controllers/EvidenceRemovalController.ts

[BI-11766
](https://companieshouse.atlassian.net/browse/BI-11766)
Add `CommonVariablesMiddleware` to `EvidenceRemovalController` to allow the user email to be set on the remove document page.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE …

Show sign out block on remove document page

---

src/views/evidence-upload.njk

https://companieshouse.atlassian.net/browse/BI-8932
When uploading evidence, instead of the user having to click a button after selecting the file, the file is now uploaded automatically after selection.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A …

BI-8932 Remove 'Upload document' button

---

terraform/groups/ecs-service/main.tf

This pr fixes the uris used to pull code from the terraform resources repo. This is to match the source for the confirmation statement web and fix the cidev-plan build in concourse.

fix the terraform sources to use correct uris

---

terraform/groups/ecs-service/locals.tf

This pr removes the cdn_host from the list of variables read from the vault as this is held in the vars file.

Remove cdn host from secrets
